/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'
import { Route as AuthenticatedAdminGalleryRouteImport } from './routes/_authenticated/admin.gallery'
import { Route as AuthenticatedAdminFinanceRouteImport } from './routes/_authenticated/admin.finance'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin.clients'
import { Route as AuthenticatedAdminAppointmentsRouteImport } from './routes/_authenticated/admin.appointments'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGalleryRoute =
  AuthenticatedAdminGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceRoute =
  AuthenticatedAdminFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAppointmentsRoute =
  AuthenticatedAdminAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/_authenticated/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/_authenticated/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/admin/appointments'
    | '/admin/clients'
    | '/admin/finance'
    | '/admin/gallery'
    | '/admin/services'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/appointments'
    | '/admin/clients'
    | '/admin/finance'
    | '/admin/gallery'
    | '/admin/services'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/admin/appointments'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/finance'
    | '/_authenticated/admin/gallery'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/gallery': {
      id: '/_authenticated/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AuthenticatedAdminGalleryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/finance': {
      id: '/_authenticated/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthenticatedAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/appointments': {
      id: '/_authenticated/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AuthenticatedAdminAppointmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAppointmentsRoute: typeof AuthenticatedAdminAppointmentsRoute
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRoute
  AuthenticatedAdminFinanceRoute: typeof AuthenticatedAdminFinanceRoute
  AuthenticatedAdminGalleryRoute: typeof AuthenticatedAdminGalleryRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAppointmentsRoute: AuthenticatedAdminAppointmentsRoute,
  AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRoute,
  AuthenticatedAdminFinanceRoute: AuthenticatedAdminFinanceRoute,
  AuthenticatedAdminGalleryRoute: AuthenticatedAdminGalleryRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
